<?xml version="1.0"?>

<robot name="gvr_bot"
    xmlns:xacro="http://playerstage.sourceforge.net/gazebo/xmlschema/#xacro"
    xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
    xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
    xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">
    
    <xacro:include filename="$(find gvrbot_simulation)/models/robots/inertial_tensors.urdf.xacro" />
    <xacro:include filename="$(find gvrbot_simulation)/models/robots/single_wheel.urdf.xacro" />
    
    <!-- Properties (Constants) -->
    <property name="M_PI" value="3.14159"/>
    
    <property name="base_size_x" value="0.70" />
    <property name="base_size_y" value="0.25" />
    <property name="base_size_z" value="0.05" />
    <property name="base_mass" value="17.92" /> <!-- GvrBot with 4 batteries weighs 39.5 lbs or 17.917 kgs -->
    
    <property name="wheel_radius_big" value="0.085" />
    <property name="wheel_size_y" value="0.0825" />
    <property name="wheel_mass" value="0.1" />

    <!-- <property name="wheel_offset_z_from_base_link" value="-${wheel_radius_big/2}" /> -->
    <property name="wheel_offset_z_from_base_link" value="0" />
    
    <macro name="gvr_base_macro">

        <link name="base_link">
            <inertial>
                <mass value="${base_mass}" />
                <origin xyz="0.0 0.0 0.0" rpy="0 0 1.57" />
                <rectangular_prism_tensor mass="${base_mass}" len_x="${base_size_x+0.10}" len_y="${base_size_y+0.14}" len_z="${base_size_z}" />
            </inertial>

            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 1.57" />
                <geometry>
                    <mesh filename="package://gvrbot_simulation/models/meshes/base_linkV3.dae"/>
                </geometry>
            </visual>

            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <geometry>
                    <box size="${base_size_x} ${base_size_y} ${base_size_z}"/>
                </geometry>
            </collision>
        </link>

        <joint name="bl_to_bm" type="fixed">
          <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
          <parent link="base_link"/>
          <child link="base_mark"/>
        </joint>

        <link name="base_mark">
            <inertial>
                <mass value="0.04" />
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <rectangular_prism_tensor mass="${base_mass}" len_x="0.02" len_y="0.02" len_z="0.02" />
            </inertial>
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <geometry>
                    <sphere radius="0.02"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0.0" />
                 <geometry>
                    <sphere radius="0.02"/>
                </geometry>
            </collision>
        </link>
        
        <tracked_wheel parent="base_link" prefix="left_0"  offset_x=" 0.25100" offset_y=" ${base_size_y / 2}" offset_z="${wheel_offset_z_from_base_link}      " reflect="1" radius="${wheel_radius_big}" height="${wheel_size_y}" mass="${wheel_mass}"/>
        <tracked_wheel parent="base_link" prefix="left_1"  offset_x=" 0.00000" offset_y=" ${base_size_y / 2}" offset_z="${wheel_offset_z_from_base_link-0.005}" reflect="1" radius="${wheel_radius_big}" height="${wheel_size_y}" mass="${wheel_mass}"/>
        <tracked_wheel parent="base_link" prefix="left_2"  offset_x="-0.25100" offset_y=" ${base_size_y / 2}" offset_z="${wheel_offset_z_from_base_link}      " reflect="1" radius="${wheel_radius_big}" height="${wheel_size_y}" mass="${wheel_mass}"/>
        <tracked_wheel parent="base_link" prefix="left_3"  offset_x=" 0.10550" offset_y=" ${base_size_y / 2}" offset_z="${wheel_offset_z_from_base_link}      " reflect="1" radius="${wheel_radius_big}" height="${wheel_size_y}" mass="${wheel_mass}"/>
        <tracked_wheel parent="base_link" prefix="left_4"  offset_x="-0.10550" offset_y=" ${base_size_y / 2}" offset_z="${wheel_offset_z_from_base_link}      " reflect="1" radius="${wheel_radius_big}" height="${wheel_size_y}" mass="${wheel_mass}"/>
        <tracked_wheel parent="base_link" prefix="left_5"  offset_x=" 0.00500" offset_y=" ${base_size_y / 2}" offset_z="${wheel_offset_z_from_base_link+0.005}" reflect="1" radius="${wheel_radius_big}" height="${wheel_size_y}" mass="${wheel_mass}"/>
        <tracked_wheel parent="base_link" prefix="right_0" offset_x=" 0.25100" offset_y="-${base_size_y / 2}" offset_z="${wheel_offset_z_from_base_link}      " reflect="1" radius="${wheel_radius_big}" height="${wheel_size_y}" mass="${wheel_mass}"/>
        <tracked_wheel parent="base_link" prefix="right_1" offset_x=" 0.00000" offset_y="-${base_size_y / 2}" offset_z="${wheel_offset_z_from_base_link-0.005}" reflect="1" radius="${wheel_radius_big}" height="${wheel_size_y}" mass="${wheel_mass}"/>
        <tracked_wheel parent="base_link" prefix="right_2" offset_x="-0.25100" offset_y="-${base_size_y / 2}" offset_z="${wheel_offset_z_from_base_link}      " reflect="1" radius="${wheel_radius_big}" height="${wheel_size_y}" mass="${wheel_mass}"/>
        <tracked_wheel parent="base_link" prefix="right_3" offset_x="-0.10550" offset_y="-${base_size_y / 2}" offset_z="${wheel_offset_z_from_base_link}      " reflect="1" radius="${wheel_radius_big}" height="${wheel_size_y}" mass="${wheel_mass}"/>
        <tracked_wheel parent="base_link" prefix="right_4" offset_x=" 0.10550" offset_y="-${base_size_y / 2}" offset_z="${wheel_offset_z_from_base_link}      " reflect="1" radius="${wheel_radius_big}" height="${wheel_size_y}" mass="${wheel_mass}"/>
        <tracked_wheel parent="base_link" prefix="right_5" offset_x=" 0.00500" offset_y="-${base_size_y / 2}" offset_z="${wheel_offset_z_from_base_link+0.005}" reflect="1" radius="${wheel_radius_big}" height="${wheel_size_y}" mass="${wheel_mass}"/>
        
       
        <gazebo>
        
        <!-- TODO: make custom plugin for this that doesn't require an imu -->
        <plugin name="diffdrive_plugin_multiwheel" filename="libdiffdrive_plugin_multi_wheel.so">                
                <alwaysOn>true</alwaysOn>
                <updateRate>50.0</updateRate>
                <leftJoints>left_0_wheel_joint left_1_wheel_joint left_2_wheel_joint left_3_wheel_joint left_4_wheel_joint left_5_wheel_joint</leftJoints>
                <rightJoints>right_0_wheel_joint right_1_wheel_joint right_2_wheel_joint right_3_wheel_joint right_4_wheel_joint right_5_wheel_joint</rightJoints>
                <wheelSeparation>${base_size_y}</wheelSeparation>
                <wheelDiameter>${wheel_radius_big*2}</wheelDiameter>
                <torque>50000</torque>
                <interface:position name="position_iface_2"/>
                <robotNamespace>/</robotNamespace>
                <robotBaseFrame>base_link</robotBaseFrame>
                <commandTopic>/gvr_bot/cmd_vel</commandTopic>
                <publishOdometryTf>1</publishOdometryTf>
                <publishOdometryMsg>1</publishOdometryMsg>
                <odometryTopic>/gvr_bot/odom</odometryTopic>
        </plugin>
     <!--  
        <plugin name="p3d_base_controller" filename="libgazebo_ros_p3d.so">
          <alwaysOn>true</alwaysOn>
          <updateRate>50.0</updateRate>
          <bodyName>base_link</bodyName>
          <topicName>/gvr_bot/ground_truth/state</topicName>
          <gaussianNoise>0.01</gaussianNoise>
          <frameName>world</frameName>
          <xyzOffsets>0 0 0</xyzOffsets>
          <rpyOffsets>0 0 0</rpyOffsets>
        </plugin>

        <plugin name="imu_controller" filename="libhector_gazebo_ros_imu.so">
          <alwaysOn>true</alwaysOn>
          <updateRate>50.0</updateRate>
          <bodyName>base_link</bodyName>
          <topicName>/gvr_bot/imu_quat</topicName>
          <accelDrift>0.0 0.0 0.0</accelDrift>
          <accelGaussianNoise>0.1 0.1 0.1</accelGaussianNoise>
          <rateDrift>0.0 0.0 0.0</rateDrift>
          <rateGaussianNoise>0.05 0.05 0.05</rateGaussianNoise>
          <headingDrift>0.0</headingDrift>
          <headingGaussianNoise>0.05</headingGaussianNoise>
        </plugin>
            -->
        </gazebo>
        
    </macro>
</robot>
